feed:
  update_interval: 1h
  limit: 20
server:
  port: 6745
  rss_key: rss_secret_key
telegram:
  bot_token: telegram_bot_token
  chat_id: 000000
  debug_mode: true
aws:
  access_key_id: access_key_id
  secret_access_key: secret_access_key
  region: eu-central-1
  bucket: tg-youtube-podcasts
