package rss

import (
	"encoding/xml"
	"wckd1/tg-youtube-podcasts-bot/db"
)

type RSS struct {
	XMLName        xml.Name     `xml:"rss"`
	Version        string       `xml:"version,attr"`
	NsItunes       string       `xml:"xmlns:itunes,attr"`
	Title          string       `xml:"channel>title"`
	Description    string       `xml:"channel>description"`
	Image          string       `xml:"channel>itunes:image"`
	Language       string       `xml:"channel>language"`
	ItunesExplicit string       `xml:"channel>itunes:explicit"`
	Category       string       `xml:"channel>itunes:category"`
	ItemList       []db.Episode `xml:"channel>item"`
}

func RSSFeed(items []db.Episode) (string, error) {
	rss := RSS{
		Version:        "2.0",
		NsItunes:       "http://www.itunes.com/dtds/podcast-1.0.dtd",
		Title:          "Private RSS feed",
		Description:    "Generated by tg-youtube-podcasts-bot",
		Image:          "https://www.clipartkey.com/mpngs/m/197-1971515_youtube-music-seamless-audio-video-switching-transparent-youtube.png",
		Language:       "ru",
		ItunesExplicit: "false",
		Category:       "Education",
		ItemList:       items,
	}

	b, err := xml.MarshalIndent(&rss, "", "  ")
	if err != nil {
		return "", err
	}

	res := `<?xml version="1.0" encoding="UTF-8"?>` + "\n" + string(b)
	return res, nil
}
