package rss

import (
	"encoding/xml"
)

func RSSFeed() (string, error) {
	// TODO: Add items

	rss := RSS{
		Version:        "2.0",
		NsItunes:       "http://www.itunes.com/dtds/podcast-1.0.dtd",
		Title:          "Private RSS feed",
		Description:    "Generated by tg-youtube-podcasts-bot",
		Link:           "",
		Language:       "ru",
		ItunesExplicit: "no",
		ItemList:       []Item{},
	}

	b, err := xml.MarshalIndent(&rss, "", "  ")
	if err != nil {
		return "", err
	}

	res := `<?xml version="1.0" encoding="UTF-8"?>` + "\n" + string(b)
	return res, nil
}
